# coding: utf-8

"""
    ORY Oathkeeper

    ORY Oathkeeper is a reverse proxy that checks the HTTP Authorization for validity against a set of rules. This service uses Hydra to validate access tokens and policies.

    The version of the OpenAPI document: v0.40.8
    Contact: hi@ory.am
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ory_oathkeeper_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_decisions(self) -> None:
        """Test case for decisions

        Access Control Decision API
        """
        pass

    def test_get_rule(self) -> None:
        """Test case for get_rule

        Retrieve a Rule
        """
        pass

    def test_get_well_known_json_web_keys(self) -> None:
        """Test case for get_well_known_json_web_keys

        Lists Cryptographic Keys
        """
        pass

    def test_list_rules(self) -> None:
        """Test case for list_rules

        List All Rules
        """
        pass


if __name__ == '__main__':
    unittest.main()
